(function () {
    let func = new RegisteredFunction({
        name: "generateHashtags",
        description:
            "Generates relevant hashtags for the selected text. The AI analyzes the content and returns a set of hashtags that can be inserted after the selection or at the end of the document.",

        // Parameters that the AI can receive
        parameters: {
            type: "object",
            properties: {
                prompt: {
                    type: "string",
                    description: "Instruction for the AI (e.g., 'Generate hashtags for this text.')",
                },
                count: {
                    type: "number",
                    description: "How many hashtags to generate (default is 5)",
                },
            },
            required: ["prompt"],
        },

        // Usage examples
        examples: [
            {
                prompt: "Generate hashtags for this text.",
                arguments: { prompt: "Generate hashtags for this text." },
            },
            {
                prompt: "Generate 10 hashtags for this paragraph.",
                arguments: {
                    prompt: "Generate 10 hashtags for this paragraph.",
                    count: 10,
                },
            },
            {
                prompt: "Create social media hashtags.",
                arguments: { prompt: "Create social media hashtags." },
            },
        ],
    });


    func.call = async function (params) {

        let count = params.count || 5;
        console.log ("Generate Hashtag function triggrerd")

        let text = await Asc.Editor.callCommand(function () {
            let doc = Api.GetDocument();
            let range = doc.GetRangeBySelect();
            let text = range ? range.GetText() : "";
            if (!text) {
                text = doc.GetCurrentWord();
                doc.SelectCurrentWord();
            }
            return text;
        });


        if (!text || text.trim().length === 0) {
            console.warn("[generateHashtags] No text selected or found. Aborting.");
            return;
        }


        let userPrompt = params.prompt || "Generate hashtags";
        let argPrompt = `${userPrompt}:\nText: ${text}\nGenerate ${count} short and relevant hashtags. Output hashtags only, separated by spaces.`;


        let requestEngine = AI.Request.create(AI.ActionType.Chat);
        if (!requestEngine) {
            console.error("[generateHashtags] AI request engine not created. Aborting.");
            return;
        }

        let isSendedEndLongAction = false;
        async function checkEndAction() {
            if (!isSendedEndLongAction) {
                await Asc.Editor.callMethod("EndAction", ["Block", "AI (" + requestEngine.modelUI.name + ")"]);
                console.log("[generateHashtags] EndAction called.");
                isSendedEndLongAction = true;
            }
        }

        await Asc.Editor.callMethod("StartAction", ["Block", "AI (" + requestEngine.modelUI.name + ")"]);

        await Asc.Editor.callMethod("StartAction", ["GroupActions"]);


        let chunks = [];

        await requestEngine.chatRequest(argPrompt, false, async function (data) {
            console.log("[generateHashtags] Received AI data chunk:", data);
            if (data) {
                chunks.push(data); // stored as is 
            }
        });

        let finalOutput = chunks.join(""); // joinied without spaces
        finalOutput = finalOutput.replace(/\s+/g, " ").trim();

        console.log("[generateHashtags] AI Request finished. Final hashtags:", finalOutput);

        if (finalOutput) {
            await checkEndAction();
            Asc.scope.data = finalOutput;
            Asc.scope.model = requestEngine.modelUI.name;

            // Insert hashtags after selection
            await Asc.Editor.callCommand(function () {
                let doc = Api.GetDocument();
                doc.MoveCursorToEnd();
                let paragraph = Api.CreateParagraph();
                paragraph.AddText(Asc.scope.data);
                doc.Push(paragraph);
            });
        } else {
            console.warn("[generateHashtags] No hashtags generated by AI.");
        }

        await checkEndAction();
        await Asc.Editor.callMethod("EndAction", ["GroupActions"]);
        console.log("[generateHashtags] GroupActions ended.");
    };

    return func;
    

})();